core-identity-uri: ${SCHEME}://${CORE_IDENTITY_HOST}:${CORE_IDENTITY_PORT}
core-gateway-uri: ${SCHEME}://${CORE_GATEWAY_HOST}:${CORE_GATEWAY_PORT}
slate-uri: ${SCHEME}://${SLATE_HOST}:${SLATE_PORT}

server:
  port: ${CORE_IDENTITY_PORT}
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
    
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password : ${REDIS_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: ${MAIL_FROM}
    app-url: ${core-identity-uri}



management:
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false

app:
  jwt:
  verification:
    strategy: URL_TOKEN  # Default verification strategy (CODE or URL_TOKEN)
    code:
      length: 6
      expiration: 300  # 5 minutes in seconds
      cooldown: 60     # 1 minute in seconds
    url-token:
      expiration: 900  # 15 minutes in seconds
      cooldown: 60     # 1 minute in seconds
    server-url: ${core-gateway-uri}
    redirect-url: ${slate-uri}


logging:
  level:
    com.benwk.ginkgoocoreidentity: trace 
    org.springframework: trace 
security:
  admin:
    ip-whitelist:
      - "10.0.0.0/8"
      - "192.168.0.0/16"
    api-key: "${ADMIN_API_KEY}"
    rate-limit: 10
  jwt:
    authority-prefix: "ROLE_"
    authorities-claim-name: "authorities"
  cors:
    allowed-origins:
      - ${core-identity-uri}
      - ${slate-uri}
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs