server:
  port: ${CORE_IDENTITY_PORT}
  shutdown: graceful

spring:
  mvc:
    static-path-pattern: /static/**
    web:
      resources:
        static-locations: classpath:/static/
        chain:
          strategy:
            content:
              enabled: true
              paths: /**
              
  lifecycle:
    timeout-per-shutdown-phase: 30s
    
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=identity
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.default_schema: identity
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: identity
    table: flyway_identity_history
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password : ${REDIS_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: ${MAIL_FROM}
    app-url: ${AUTH_SERVER}


management:
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false

app:
  domain-name: ${APP_DOMAIN}
  dev-uris: ${DEV_SLATE_URI}
  jwt:
  auth-server-uri: ${AUTH_SERVER}
  verification:
    strategy: CODE  # Default verification strategy (CODE or URL_TOKEN)
    code:
      length: 6
      expiration: 300  # 5 minutes in seconds
      cooldown: 60     # 1 minute in seconds
    url-token:
      expiration: 900  # 15 minutes in seconds
      cooldown: 60     # 1 minute in seconds
    server-url: ${core-gateway-uri}

security:
  admin:
    ip-whitelist:
      - "10.0.0.0/8"
      - "192.168.0.0/16"
    api-key: "${ADMIN_API_KEY}"
    rate-limit: 10
  jwt:
    authority-prefix: "ROLE_"
    authorities-claim-name: "authorities"
  cors:
    allowed-origins:
      - ${core-gateway-uri}
      - ${AUTH_CLIENT}
      - ${SLATE_URI}

springdoc:
  api-docs:
    enabled: true
    path: /api/identity/v3/api-docs
  swagger-ui:
    enabled: true
    csrf:
      enabled: true
    path: /api/identity/swagger-ui.html
      
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.web.cors: ${LOG_LEVEL_SPRING_WEB_CORS:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:DEBUG}
    com.ginkgooai: ${LOG_LEVEL_GINKGOOAI:DEBUG}